### ISSUE TITLE
[Suggestion] Optionally create a Mac executable instead of a Playground when appropriate.

### ISSUE THREAD

**Issue by tgrapperon** [SwiftPackageIndex/SPI-Playgrounds-Releases#11]
Hello!
I never was able to make a macOS Swift Playground work reliably. There is always a moment when they only execute if they run automatically, with manual runs only showing a never-ending spinner.
Furthermore, contextual interactions are different than what we get when editing a standard swift file in Xcode. I find iOS playgrounds more stable for some reason, but all of this makes Swift Playgrounds an extremely awkward and brittle environment in my opinion.

This is the kind of failure I just had when trying to text `swift-async-algorithm`. As a workaround, I created a SwiftPM Mac executable that provides almost the same functionality as a playground, but it was needlessly convoluted to set up with Xcode: You have to create a swift package, then change the types to executable, then add `@main`, and then declare manually the dependency to the package you want to test, as the package and target levels. All of this is straightforward, and if there are maybe command-line arguments to perform the same thing, it is always more cumbersome than having it created automatically.

All of this is not caused by SPI-Playgrounds, which is a very nice tool. I think it would be fantastic if it provided the option to create a mac executable instead of a playground when it's possible (that is when the package supports the `.mac` platform).
It is also probable that iOS Playgrounds (the `.swiftpm` ones) can be created otherwise, but this can be realized easily enough with Xcode.
Thanks!

**Comment by finestructure** [comment]
Hi Thomas, thanks for the report!

I've noticed that sometimes playgrounds can be a bit weird indeed. What typically works for me is to close and re-open the playground. That seems to shake things loose.

Creating an entire executable project is one way to work around it but I feel like the main selling point of our playgrounds integration is the fact that you're getting the live results.

I think the best fix for this would be if playgrounds were more reliable. Is there perhaps a reproducible case that we could take to the Xcode team? If you've got a FB number I suspect we could alert some folks to it :)

**Comment by tgrapperon** [comment]
Thanks Sven.

I have the same issue with vanilla playgrounds on Mac, since the dawn of times. If automatic run is disabled, there is always a moment where they'll stop evaluating, but it's not always reproducible. I have absolutely no hope in old-style playgrounds getting better, they have the same kind of issue since Swift 1.0. For some reason, iOS playgrounds seem more reliable, and the new .swiftpm targets are quite good too (but they are SwiftPM executables under the hood).

Let say that I want to quickly check some async algorithm using `swift-async-algorithm`, it will not matter very much to me if I'm running a playground that will print in the console, or a single file Mac executable that will also print in the console. The Mac executable will simply execute faster than playgrounds because it doesn't need to display extended information, and it also works more reliably, be debuggable and have better contextual actions.

I get the selling point around Playgrounds. I was not suggesting to replace them, but to offer an option to generate a macOS executable package instead when possible. It is likely that this approach can be extended to .swiftpm packages and will allow to generate iPad compatible playgrounds.

**Comment by finestructure** [comment]
That's odd though. While I _do_ see issues around playgrounds occasionally it's nowhere near as bad as you describe! I do use them quite frequently and believe me it works quite well. I wonder what's going on here?

As to adding the feature you suggest: I can see it being useful. I'm not sure if you're aware, SPI Playgrounds is using https://github.com/finestructure/Arena under the hood to generate the playground.

Maybe a good intermediate step would be to add the functionality you seek there and then there'd be at least a command line option to quickly generate an executable?
