### ISSUE TITLE
Generates Playground with deprecated 'package(name:url:from:)'

### ISSUE THREAD

**Issue by byaruhaf** [SwiftPackageIndex/SPI-Playgrounds-Releases#12]
The app generates a playground with the deprecated `'package(name:url:from:)'  `

`'package(name:url:from:)' ` is deprecated: use `package(url:from:)` instead

can the app be update to use `package(url:from:)` to remove this warning.

**Comment by finestructure** [comment]
Thanks for the report, @byaruhaf . This should be addressed in the underlying tool Arena: https://github.com/finestructure/Arena/issues/85 but the release of "SPI Playgrounds" is currently held up due to an unrelated issue.

We hope to have a new release out soon!

**Comment by daveverwer** [comment]
I'm planning to look at the unrelated issue this coming week. Sorry for the inconvenience!

**Comment by byaruhaf** [comment]
Thank guys, no inconvenience, will be waiting for the update.

**Comment by finestructure** [comment]
This update has now been release (version 1.1.0). Sorry for the long delay, @byaruhaf !
