### ISSUE TITLE
Problem: Images residing in a swift package are not found.

### ISSUE THREAD

**Issue by billh0420** [SwiftPackageIndex/SPI-Playgrounds-Releases#9]
I used SPI-Playgrounds in order to test a swift package residing on GitHub.

I added some code to build an image from images resource of the package, but the image was not found.

Is this a known problem?

**Comment by finestructure** [comment]
How did you add the image exactly? Does it work in a standalone playground?

**Comment by billh0420** [comment]
I used Swift Package Index to search on "card image".  I selected the only match "WHPlayingCardImageKit".

I clicked "Try in a playground" to setup the playground with the dependent packages.

In Content, I had the following code:


`

   import PlaygroundSupport
   import SwiftUI
   import SpriteKit

   import WHPlayingCardImageKit
   import WHPlayingCardKit
   import WHCrossPlatformKit

   let rank = Rank.queen
   let suit = Suit.spades
   let card = Card(rank: rank, suit: suit)
   let defaultCardSize = CardImageAtlas.cardImageAtlasDefaultCardSize
   let fullCardImageMaker = FullCardImageMaker(defaultCardSize: defaultCardSize, scaleFactor: 1.0)
   let imageQS = fullCardImageMaker.makeCardImageFor(rank: rank, suit: suit)
   var someImages:[NSImage] = []
   populateSomeImages()

   struct ContentView: View {
       var body: some View {
           VStack {
               Text("Hello World")
                   .foregroundColor(.red)
                   .fontWeight(.bold)
               Image(nsImage: imageQS)
           }
       }
   }

   PlaygroundPage.current.setLiveView(ContentView())
   print("Done")

   func populateSomeImages() {
       for rank in Rank.allRanks {
           if rank == Rank.five {
               break
           }
           for suit in Suit.all4Suits {
               if suit == Suit.hearts {
                   break
               }
               let image = fullCardImageMaker.makeCardImageFor(rank: rank, suit: suit)
               someImages.append(image)
           }
       }
   }


`

The problem line is "let imageQS = fullCardImageMaker.makeCardImageFor(rank: rank, suit: suit)"

In a standard playground, I couldn't figure out how to add packages.

It does work if I use Xcode to create a normal app.

**Comment by finestructure** [comment]
I'm not familiar with this package in particular but in general, the way you load resources is by adding them to the `Resources` folder and then using `Bundle.main.url(forResource:withExtension:)`:

```
import Foundation

let fileURL = Bundle.main.url(forResource: "foo", withExtension: "txt")!
print(try String(contentsOf: fileURL))
```

![CleanShot 2022-02-06 at 02 51 25@2x](https://user-images.githubusercontent.com/65520/152665083-0d82ddeb-ac62-4455-a049-5a1bc429c56f.png)

**Comment by billh0420** [comment]
The WHPlayingCardImageKit  does the loading. The code is:

```swift

            guard let path = Bundle.module.path(forResource: resourceName, ofType: "png") else { throw DrawFullCardError.invalidPath }
            guard let image = WHImage(contentsOfFile: path) else { throw DrawFullCardError.invalidImage }

```

The resource is in the bundle of the package, not in the resource of the app or the playground.

**Comment by finestructure** [comment]
Ah, I see. Running your full example, I'm getting

```
WHPlayingCardImageKit/resource_bundle_accessor.swift:27: Fatal error: unable to find bundle named WHPlayingCardImageKit_WHPlayingCardImageKit
```

in the console. It looks like package resources (which are fairly recent) aren't yet supported in Xcode playgrounds. `resource_bundle_accessor.swift` is an [autogenerated file](https://forums.swift.org/t/linux-extending-resource-bundle-accessor-swift/54497) that's probably not taking this scenario into account.

I'm afraid in this case you'll have to set up a small macOS app project to test the package :(

**Comment by billh0420** [comment]
Ok. I am not really testing the package since I am the author. I was trying to see what documentation that I needed to provide for a person downloading the package (especially if they are using Swift Package Index).

It would have been nice to instruct how they could use the option "Try in playground".

I will just give the usual instructions on how to use the package by making a normal app.

Thanks for your help.

**Comment by finestructure** [comment]
Ah, I see (again :D).

I think this would be fixable if you exposed a way in the API to provide `Bundle.main` from the playground instead of `Bundle.module` that you're using.

What I mean is to change to this:

```
    class func drawCardFaceWithResourceName(_ resourceName:String, targetFrame:CGRect, bundle: Bundle = .module) {
        do {
            guard let path = bundle.path(forResource: resourceName, ofType: "png") else { throw DrawFullCardError.invalidPath }
```

(which would be need to be wired through up to `makeCardImageFor`). This would keep the API unchanged but in a playground you could do:

```
let imageQS = fullCardImageMaker.makeCardImageFor(rank: rank, suit: suit, bundle: .main)
```

You could also maybe just try the alternative `Bundle.main` in case image loading via `Bundle.module` fails (if indeed that's what's happening).

Hope that helps!

**Comment by billh0420** [comment]
Before I converted to packages, I used Bundle.main. When I converted to packages, that no longer worked and I switch to Bundle.module (as some google search revealed). Not sure one can use Bundle.main to access a bundle in a package (ie module).

I'm not going to put effort into seeing if I can provide a work around since I don't envision my package being used in playgrounds.
